version: 1
send_anonymous_usage_stats: true
project_id: a5eda732-9497-4af2-9c83-43af20c2de16
plugins:
  extractors:
  - name: tap-ethereum
    namespace: tap_ethereum
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    settings:
    - name: ethereum_rpc
    - name: contracts
    - name: etherscan_api_key
    - name: confirmations
    - name: batch_size
    - name: concurrency
    config:
      concurrency: 50
      batch_size: 100
      confirmations: 12
      contracts:
      - name: AloeBlend
        abi: ./examples/aloe-blend/abi.json
        instances:
        - name: USDC/WETH 0.05% cUSDC cETH
          address: '0x33cB657E7fd57F1f2d5f392FB78D5FA80806d1B4'
          start_block: 14170520
        - name: FEI/TRIBE 0.05% fFEI 8 fTRIBE 8
          address: '0x0B76ABb170519C292da41404fDc30Bb5BEf308Fc'
          start_block: 14164593
        - name: WBTC/WETH 0.05% yvWBTC yvWETH
          address: '0xE801c4175A0341e65dFef8F3B79e1889047AfEbb'
          start_block: 14164820
        - name: RAI/WETH 0.30% fRAI 9 yvWETH
          address: '0x37dc6FCb5C03d46b097B094785c9fA557aa32fd4'
          start_block: 14261737
        - name: WETH/LOOKS 0.30% cETH LooksRare Staking
          address: '0x021016FbB4d3AAeaA440508C5E06Ce8c1039FCCD'
          start_block: 14279169
        events:
        - Transfer
        getters:
        - getInventory
        - totalSupply
  loaders:
  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
    config:
      add_metadata_columns: true
      flush_all_streams: true
      batch_size_rows: 100
